In [4]:
# ЗАДАНИЕ № 1
import numpy as np

N = 15
numpy_array = np.arange(N-1,-1,-1)
print(numpy_array)



[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [6]:
# ЗАДАНИЕ № 2

N = 10
matr_diag = np.diag(np.arange(N-1, -1, -1), k=0)
sum_diag = sum(sum(matr_diag))

print(matr_diag)
print("Сумма значений на диагонали", sum_diag)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений на диагонали 45


In [7]:
# ЗАДАНИЕ № 3

from numpy import linalg

left_side = np.array([[4,2,1],[1,3,0],[0,5,4]])
right_side = np.array([4,12,-3])

# найдем корни и выведем на экран
roots_of_equation = linalg.solve(left_side, right_side)
print(roots_of_equation)

# проверим решение
if np.allclose(np.dot(left_side, roots_of_equation), np.float64(right_side)):
    print("Решение правильное")
else:
    print("Решение неправильное")

[ 0.46666667  3.84444444 -5.55555556]
Решение правильное


In [15]:
# ЗАДАНИЕ № 4

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])


def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

# переменная для хранения косинуса угла
max_cosine = 0
# переменная для хранения user_ID
user_ID = 0

# пройдемся циклом по user_ID и найдем user_ID с максимальным значением косинуса угла
for num_str in range(0, users_stats.shape[0], 1):
    if max_cosine <= cosine(users_stats[num_str], next_user_stats):
        max_cosine = cosine(users_stats[num_str], next_user_stats) 
        user_ID = num_str +1
        
print("Самый похожий пользователь user_ID =", user_ID,",", "косинус угла равен =", max_cosine)





Самый похожий пользователь user_ID = 8 , косинус угла равен = 0.9486832980505138
