In [55]:
#a)
import numpy as np 
import matplotlib.pyplot as plt

# Диагональная, ортогональная, но не единичная(!)
matr_diag_orto_not_edinich = np.array([[-1,0,0],
                                      [0,-1,0],
                                      [0,0,-1]])                          

matr_trans = matr_diag_orto_not_edinich.transpose()

print(matr_diag_orto_not_edinich)
print(matr_trans)
print(matr_trans.dot(matr_diag_orto_not_edinich))


[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [56]:
# b)
# Верхнетреугольная, ортогональная - не смог найти, есть ли такая, прошу обьяснить?

In [46]:
# c)
# Нижнетреугольная, ортогональная - не смог найти, есть ли такая, прошу обьяснить?

In [57]:
# d)
# Матрица, у которой определитель = 1, и все элементы не равны 0
matr = np.array([[np.cos(np.pi/6),np.sin(np.pi/6)],
                [-np.sin(np.pi/6),np.cos(np.pi/6)]])                         

matr_trans = matr.transpose()

print(matr)
print(matr_trans)
print(matr_trans.dot(matr))
print("det = ",np.linalg.det(matr))


[[ 0.8660254  0.5      ]
 [-0.5        0.8660254]]
[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]
[[ 1.00000000e+00 -7.43708407e-18]
 [-7.43708407e-18  1.00000000e+00]]
det =  1.0


In [54]:
# Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])

l, v = np.linalg.eig(m)
print("собственные значения - ", l)
print("собственные вектора - ", v)

собственные значения -  [1. 4.]
собственные вектора -  [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]
